version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root

