version: '3.1'

services:


  backend:
    image: unclechuen/ar-backend
    restart: always
    ports:
      - 8080:8080
  frontend:
    image: unclechuen/ar-frontend
    restart: always
    ports:
      - 3000:3000

  db:
    image: mariadb
    restart: always
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root

