version: '3.1'

services:

  backend:
    image: unclechuen/ar-backend
    restart: always
    ports:
      - 8080:8080
  frontend:
    image: unclechuen/ar-frontend
    restart: always
    ports:
      - 3000:3000
